### ISSUE TITLE
No default constructor for defined classes

### ISSUE THREAD

**Issue by omegahh** [cartoonist/kseqpp#5]
Hi, I want to make a map of {int -> SeqStreamOut}, for output reads to different files according to the int key. but the compiler says that "no matching constructor for initialization of SeqStreamOut", any could help me? Thank you

**Comment by cartoonist** [comment]
Hi,

It is not straightforward for me how to implement an empty instance of `SeqStreamOut` or `SeqStreamIn` since the worker thread responsible for writing the records into the underlying file is started when constructing an instance. So, the constructor should get at least the file path. As a workaround, you can make a map of `<int, std::unique_ptr<SeqStreamOut>>`. Does something like this work for you?

```c++
  std::unordered_map< int, std::unique_ptr< klibpp::SeqStreamOut > > map;
  map[1] = std::make_unique< klibpp::SeqStreamOut >( "file1.fq" );
  map[2] = std::make_unique< klibpp::SeqStreamOut >( "file2.fq" );
  klibpp::KSeq r1, r2;
  /* populating r1 and r2... */
  *(map[1]) << r1;
  *(map[2]) << r2;
```

**Comment by omegahh** [comment]
Thank you, it works
